server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: dummy-backend
          uri: http://localhost:8085
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/gatemind_client
    username: tanishq
    password: tanishq123

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health

gatemind:
  rate-limit:
    requests: 5
    window-seconds: 60

clients:
  service:
    base-url: http://localhost:8081
